package com.Maven_Project;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;
import org.openqa.selenium.WebDriver;
import com.SDPs.Page_Object_Manager2;
import com.helper.File_Reader_Manager;

public class Mini_Project12 extends Base_Class {
	static Logger log = Logger.getLogger(Mini_Project12.class);
	public static WebDriver driver = getBrowser("Chrome");
	public static Page_Object_Manager2 pom = new Page_Object_Manager2(driver);
	public static void main(String[] args) throws Throwable  {
		PropertyConfigurator.configure("log4j.properties");
		String url = File_Reader_Manager.getInstanceFRM().getInstanceCR().getUrl();
		url(url);
		sleep(1000);
		log.info("Url Launch Succesfully");
		String username = File_Reader_Manager.getInstanceFRM().getInstanceCR().getUsername();
		inputValueElement(pom.getInstancelP().getuser_Name(), username);
		String password = File_Reader_Manager.getInstanceFRM().getInstanceCR().getPassword();
		inputValueElement(pom.getInstancelP().getpassWord(), password);
		clickOnElement(pom.getInstancelP().getlogin_Button());
		sleep(2000);
		log.info("SignIn Done");
		String location = File_Reader_Manager.getInstanceFRM().getInstanceCR().getLocation();
		dropDown("index", pom.getInstancesH().getHotel_Location(), location);
		sleep(1000);
		String hotelname = File_Reader_Manager.getInstanceFRM().getInstanceCR().getHotelname();
		dropDown("index", pom.getInstancesH().getHotel_Name(), hotelname);
		sleep(1000);
		String roomtype = File_Reader_Manager.getInstanceFRM().getInstanceCR().getRoomtype();
		dropDown("text", pom.getInstancesH().getRoom_Type(), roomtype);
		sleep(1000);
		String roomno = File_Reader_Manager.getInstanceFRM().getInstanceCR().getRoomno();
		dropDown("value", pom.getInstancesH().getRoom_No(), roomno);
		sleep(1000);
		clear(pom.getInstancesH().getCheckIn());
		String checkin = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCheckin();
		inputValueElement(pom.getInstancesH().getCheckIn(), checkin);
		sleep(1000);
		clear(pom.getInstancesH().getCheckOut());
		String checkout = File_Reader_Manager.getInstanceFRM().getInstanceCR().getCheckout();
		inputValueElement(pom.getInstancesH().getCheckOut(), checkout);
		sleep(1000);
		String adultno = File_Reader_Manager.getInstanceFRM().getInstanceCR().getAdultno();
	    dropDown("value", pom.getInstancesH().getAdult_No(), adultno);
		sleep(1000);
		String childno = File_Reader_Manager.getInstanceFRM().getInstanceCR().getChildno();
		dropDown("value", pom.getInstancesH().getChild_No(), childno);
		sleep(1000);
		clickOnElement(pom.getInstancesH().getSubmit_Button());
		sleep(2000);
		log.info("Room details and CheckIN Details Entered");
		clickOnElement(pom.getInstancehS().getSelect_Hotel());
		clickOnElement(pom.getInstancehS().getContinue_Button());
		sleep(2000);
		log.info("Room Selected");
		String firstName = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 15 , 5);
		inputValueElement(pom.getInstancebH().getFirst_Name(), firstName);
		String lastName = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 16 , 5);
		inputValueElement(pom.getInstancebH().getLast_Name(), lastName);
		String address = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 17 , 5);
	    inputValueElement(pom.getInstancebH().getAddress(), address);	
		String cardNo = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 18 , 5);
		inputValueElement(pom.getInstancebH().getCard_No(), cardNo);
		String cardType = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 19 , 5);
		dropDown("text", pom.getInstancebH().getCard_Type(), cardType);
		sleep(1000);
		String expireMonth = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 20 , 5);
		dropDown("index", pom.getInstancebH().getExpire_Month(), expireMonth);
		sleep(1000);
		String expireYear = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 21 , 5);
		dropDown("value", pom.getInstancebH().getExpire_Year(), expireYear);
		sleep(1000);
		String cardCvv = particular_Data("C:\\Users\\rajes\\eclipse-workspace\\Maven_Project\\Test Case.xlsx", 22 , 5);
		inputValueElement(pom.getInstancebH().getCard_Cvv(), cardCvv);
		log.info("Personal Details and Card Details Filled");
		clickOnElement(pom.getInstancebH().getBook_Now());
		log.info("Room Booked Succesfully");
	    }
        }
